### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by djeedai** [djeedai/weldr#2]
## weldr

- [x] Implement all basic LDraw commands (1 to 5) (aae85ec77ab3466e87c961744ff58637d67a87c2)
- [x] Implement sub-file resolution and recursive parsing (7cc74c61c91671c1352dcb427e2c6dc634d60305)
- [x] Add error handling (5758d20327ab93d89845438350ea5cdba3bb9217)
- [x] Expose iterators (1d5eac6b31266c8628b9c414afd9dd057db08a7d):
  - [x] for all non-sub-file commands (default behavior; `iter()`), transparently descending into sub-files
  - [x] for all commands local to a file (`local_iter()`) including sub-file commands, without dereferencing
- [ ] Implement common meta command extensions
  - [ ] !HISTORY - File Changes History
  - [x] !COLOUR - Colour Definition (372ef2462961bb32815f660d24c7bec19505fd08)
  - [ ] BFC - Back Face Culling
  - [ ] !TEXMAP - Texture Mapping
  - [x] !CATEGORY (afe45ebe07fff6ed8a5c18c182c2ff72481f974a)
  - [x] !KEYWORDS (afe45ebe07fff6ed8a5c18c182c2ff72481f974a)
  - [x] Multi-Part Document (#26) (01c1359bab2595b1c263b1706465be79ded15b3f)
- [x] Add basic filesystem-based resolver (possibly in `examples/` only)
- [x] Add source map cache to avoid re-loading and re-parsing the same sub-files
- [ ] Benchmark : entire LDraw official catalog (speed + correctness)

## weldr-bin

- [x] Handle parts catalog location configuration (5db56b999140ed4210b876f7f31be5590f6647d1)
- [x] Fix bug with some round parts looking truncated (_e.g._ `6143.dat`) (94fd91f0fcb3e75272e50dca68b074c3eb068937)
- [ ] Merge duplicate vertices
- [ ] Handle various primitives : line, triangle, quad (instead of current all-triangle discard-lines) (lines: efaa14a5459877198e2775ebe3c00e99253167d9)
- [ ] `convert gltf`: Output glTF buffer inline inside JSON to allow `stdout` output
